(lang dune 3.20)

(name vsharp)

(version 0.1.0)

(generate_opam_files true)

(source
 (github PeterGriffinSr/vsharp))

(authors "Codezz-Ops")

(maintainers "Codezz-Ops")

(license MIT)

(documentation https://url/to/documentation)

(package
 (name vsharp)
 (synopsis "Purely functional programming language.")
 (description "VSharp is a purely functional programming language.")
 (depends ocaml dune)
 (tags
  ("functional" "language" "typed" "static-typing")))
