type span = Lexing.position * Lexing.position
(** The [span] type represents a range of positions in the source code. *)

(** The [t] type represents all tokens. *)
type t =
  | Integer of int64 * span  (** Integer literal. *)
  | FloatingPoint of float * span  (** Floating-point literal. *)
  | String of string * span  (** String literal. *)
  | Identifier of string * span  (** Identifier. *)
  | Let of span  (** [let] keyword. *)
  | Function of span  (** [function] keyword. *)
  | If of span  (** [if] keyword. *)
  | Then of span  (** [then] keyword. *)
  | Else of span  (** [else] keyword. *)
  | Match of span  (** [match] keyword. *)
  | Case of span  (** [case] keyword. *)
  | In of span  (** [in] keyword. *)
  | IntegerType of span  (** [int] type keyword. *)
  | FloatingPointType of span  (** [float] type keyword. *)
  | StringType of span  (** [string] type keyword. *)
  | BooleanType of span  (** [bool] type keyword. *)
  | UnitType of span  (** [unit] type keyword. *)
  | LeftParen of span  (** [(] punctuation. *)
  | RightParen of span  (** [)] punctuation. *)
  | LeftBrace of span  (** [{] punctuation. *)
  | RightBrace of span  (** [}] punctuation. *)
  | LeftBracket of span  (** [\[] punctuation. *)
  | RightBracket of span  (** [\]] punctuation. *)
  | Plus of span  (** [+] operator. *)
  | Minus of span  (** [-] operator. *)
  | Asterisk of span  (** [*] operator. *)
  | Slash of span  (** [/] operator. *)
  | Equal of span  (** [=] operator. *)
  | NotEqual of span  (** [<>] operator. *)
  | Less of span  (** [<] operator. *)
  | Greater of span  (** [>] operator. *)
  | Comma of span  (** [,] punctuation. *)
  | Colon of span  (** [:] punctuation. *)
  | Arrow of span  (** [->] punctuation. *)
  | EndOfFile of span  (** End-of-file marker. *)

val to_string : t -> string
(** [to_string tok] returns a human-readable string representation of [tok]. *)
