let to_string = function
  | Parser.Integer (i, _) -> Printf.sprintf "Integer(%Ld)" i
  | Parser.FloatingPoint (f, _) -> Printf.sprintf "Float(%g)" f
  | Parser.String (s, _) -> Printf.sprintf "String(%S)" s
  | Parser.Identifier (id, _) -> Printf.sprintf "Identifier(%s)" id
  | Parser.Boolean (b, _) -> Printf.sprintf "Boolean(%b)" b
  | Parser.Unit ((), _) -> Printf.sprintf "Unit()"
  | Parser.Let _ -> "Let"
  | Parser.If _ -> "If"
  | Parser.Then _ -> "Then"
  | Parser.Else _ -> "Else"
  | Parser.Match _ -> "Match"
  | Parser.IntegerType _ -> "IntegerType"
  | Parser.FloatingPointType _ -> "FloatingPointType"
  | Parser.StringType _ -> "StringType"
  | Parser.BooleanType _ -> "BooleanType"
  | Parser.UnitType _ -> "UnitType"
  | Parser.LeftParen _ -> "LeftParen"
  | Parser.RightParen _ -> "RightParen"
  | Parser.LeftBrace _ -> "LeftBrace"
  | Parser.RightBrace _ -> "RightBrace"
  | Parser.LeftBracket _ -> "LeftBracket"
  | Parser.RightBracket _ -> "RightBracket"
  | Parser.Plus _ -> "Plus"
  | Parser.Minus _ -> "Minus"
  | Parser.Asterisk _ -> "Asterisk"
  | Parser.Slash _ -> "Slash"
  | Parser.Equal _ -> "Equal"
  | Parser.NotEqual _ -> "NotEqual"
  | Parser.Less _ -> "Less"
  | Parser.Greater _ -> "Greater"
  | Parser.Comma _ -> "Comma"
  | Parser.Colon _ -> "Colon"
  | Parser.Pipe _ -> "Pipe"
  | Parser.Cons _ -> "Cons"
  | Parser.Arrow _ -> "Arrow"
  | Parser.Semicolon _ -> "Semicolon"
  | Parser.EndOfFile _ -> "EOF"
