let to_string = function
  | Parser.Integer (i, _) -> Printf.sprintf "Integer(%Ld)" i
  | Parser.FloatingPoint (f, _) -> Printf.sprintf "Float(%g)" f
  | Parser.String (s, _) -> Printf.sprintf "String(%S)" s
  | Parser.Identifier (id, _) -> Printf.sprintf "Identifier(%s)" id
  | Parser.Boolean (b, _) -> Printf.sprintf "Boolean(%b)" b
  | Parser.Unit ((), _) -> Printf.sprintf "Unit()"
  | Parser.KwLet _ -> "Let"
  | Parser.KwIf _ -> "If"
  | Parser.KwThen _ -> "Then"
  | Parser.KwElse _ -> "Else"
  | Parser.KwMatch _ -> "Match"
  | Parser.KwImport _ -> "Import"
  | Parser.KwData _ -> "Data"
  | Parser.IntegerType _ -> "IntegerType"
  | Parser.I8Type _ -> "Int8Type"
  | Parser.I16Type _ -> "Int16Type"
  | Parser.I32Type _ -> "Int32Type"
  | Parser.I64Type _ -> "Int64Type"
  | Parser.FloatingPointType _ -> "FloatingPointType"
  | Parser.F32Type _ -> "FloatingPoint32Type"
  | Parser.F64Type _ -> "FloatingPoint64Type"
  | Parser.StringType _ -> "StringType"
  | Parser.BooleanType _ -> "BooleanType"
  | Parser.UnitType _ -> "UnitType"
  | Parser.ListType _ -> "ListType"
  | Parser.LeftParen _ -> "LeftParen"
  | Parser.RightParen _ -> "RightParen"
  | Parser.LeftBrace _ -> "LeftBrace"
  | Parser.RightBrace _ -> "RightBrace"
  | Parser.LeftBracket _ -> "LeftBracket"
  | Parser.RightBracket _ -> "RightBracket"
  | Parser.Plus _ -> "Plus"
  | Parser.Minus _ -> "Minus"
  | Parser.Asterisk _ -> "Asterisk"
  | Parser.Slash _ -> "Slash"
  | Parser.Equal _ -> "Equal"
  | Parser.NotEqual _ -> "NotEqual"
  | Parser.Less _ -> "Less"
  | Parser.Greater _ -> "Greater"
  | Parser.Comma _ -> "Comma"
  | Parser.Colon _ -> "Colon"
  | Parser.Pipe _ -> "Pipe"
  | Parser.Cons _ -> "Cons"
  | Parser.Arrow _ -> "Arrow"
  | Parser.Underscore _ -> "Underscore"
  | Parser.Dot _ -> "Dot"
  | Parser.Quote _ -> "Quote"
  | Parser.DotDot _ -> "DotDot"
  | Parser.EndOfFile _ -> "EOF"
